# Generated by Django 3.1.7 on 2021-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_bloglikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikes',
            name='dislikes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
    ]
