# Generated by Django 3.1.7 on 2021-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210903_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikes',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
