# Generated by Django 3.1.7 on 2021-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210902_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
