# Generated by Django 3.1.7 on 2021-09-02 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blogpost_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 2, 11, 20, 32, 852934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
