# Generated by Django 3.1.7 on 2021-09-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210903_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikes',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
