# Generated by Django 3.1.7 on 2021-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20210903_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about_writer',
            field=models.TextField(default=''),
        ),
    ]
