# Generated by Django 3.1.7 on 2021-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blogpost_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
