# Generated by Django 3.1.7 on 2021-09-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_myuser_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImages',
        ),
    ]
