# Generated by Django 3.1.7 on 2021-09-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_delete_blogimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogparagraph',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogParagraphImage/%m/%d/'),
        ),
    ]
